name: CI

on: [push, pull_request]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true

  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile
    
  # publish-docker:
  #   runs-on: ubuntu-latest
  #   needs:
  #    - build-docker
  #    - build-node

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Publish the Docker image
  #     if: github.ref == 'refs/heads/master'
  #     run: |
  #       docker build . --file Dockerfile --tag ${{ secrets.registry_host }}/${{ github.repository }}:latest
  #       docker login ${{ secrets.registry_host }} --username ${{ secrets.registry_user }} --password ${{ secrets.registry_password }}
  #       docker push ${{ secrets.registry_host }}/${{ github.repository }}:latest
